### ISSUE TITLE
Aggregated duplicates are confusing

### ISSUE THREAD

**Issue by albinkjellin** [sodadata/soda-core#1273] opened 2022-04-15 08:07 UTC
I have these checks and none of them fail:

``` yaml
  - duplicate_count(product_name) = 5
  - duplicate_count(product_category) = 3
  - duplicate_count(product_name, product_category) = 15
```
To me it seems like duplicate_count(product_name, product_category) should result in 8 or the number of duplicates of the combination of product_name and product_category.

**Comment by jasonicarter** [comment] 2022-05-03 16:33
> the number of duplicates of the combination of product_name and product_category.
I think that's what it is showing...

**Example**
product_name = `1, 1, 2, 2, 3, 3`
product_category = `A, A , B, B, C, C, D, D, E, E`

Number of duplicates of the combination (product_name, product_category) = 15

1. A1, A1
2. A2, A2
3. A3, A3
4. B1, B1
5. B2, B2
6. B3, B3
7. C1, C1
8. C2, C2
9. C3, C3
10. D1, D1
11. D2, D2
12. D3, D3
13. E1, E1
14. E2, E2
15. E3, E3

**Comment by m1n0** [comment] 2023-01-05 21:58
Yes that is correct, running duplicate check with multiple columns creates permutations and counts the duplicates in the result, I believe this is working as intended, so closing. Please reopen this one @albinkjellin in case I misunderstood or if there is something that needs to be fixed.

**Closed by m1n0** 2023-01-05 21:58 UTC
