### ISSUE TITLE
unable to use camel case postgres columns with soda contracts

### ISSUE THREAD

**Issue by TianyuanCai** [sodadata/soda-core#2053] opened 2024-04-14 03:39 UTC
When evaluating contracts, camel cased columns such as `countryId` doesn't get double-quoted before being templated into the sql query. As a result, this column won't be recognized, and the query would fail. I've tried several ways of escaping the quote in yaml to no avail. Do you have any suggestions for how to perform validation on camel case columns?

```yaml
dataset: country

columns:
  - name: name
    checks: 
      - type: no_missing_values
  - name: countryId
    checks: 
      - type: no_missing_values
```

**Comment by tools-soda** [comment] 2024-04-14 03:40
SAS-3231

**Comment by tombaeyens** [comment] 2024-06-26 08:16
Duplicate of #2108

**Closed by tombaeyens** 2024-06-26 08:16 UTC
Labels: contract
